### ISSUE TITLE
[Feature] Server will unpause after X seconds + Idea

### ISSUE THREAD

**Issue by MikkelDK** [brennanmcmicking/PugCommands#1]
Hi,

It could be nice if it's possible to add..so if "no one" did unpause. and it will unpause automatically after X seconds. =)

Could too be nice, if you could adding;
!timeout - a command with timeout function (built-in the script) 0/3 - 30 seconds (possible to edit from .sp file)

Thank you!

**Comment by MikkelDK** [comment]
@brennanmcmicking I hope you are still active with SourceMod! =) and sorry for disturb =D

**Comment by brennanmcmicking** [comment]
Thank you for the suggestion! I will add it in the reworked version of this plugin that I am working on. It is in development and viewable at github.com/brennanmcmicking/pugreworked

**Comment by MikkelDK** [comment]
Let me know, once it is released. willing to "beta-test" since I will use your "old version".

And make command for it to be "loaded"
As example:
!mix/!scrim => so people direct after can use !ready or !gaben for ready-up =D

**Comment by MikkelDK** [comment]
Oh btw. @brennanmcmicking 

I forgot to say, you should make on "pugreworked" so it **DON'T** count GOTV as a player! =)
Because I use GOTV, with simple plugin "AutoRecord" =D so it will start automatically after it loaded :D

**Comment by brennanmcmicking** [comment]
Check out the [PugReworked beta](https://github.com/brennanmcmicking/PugReworked/releases/tag/3.0b) that I just released. It doesn't have the pause feature implemented yet but I will add it tomorrow.

**Comment by MikkelDK** [comment]
Yes. @brennanmcmicking 

I will close this, and typo over the PugReworked! =) 
Thank you  <3
